### PR TITLE
Improve build system flexibility and update README

### PR DESCRIPTION
**Pull request by antecrescent**
Please refer to the commit messages for a detailed explanation for these changes.

[Makefile conventions](https://www.gnu.org/software/make/manual/html_node/Makefile-Conventions.html): 
I tried to improve the build system flexibility for distro packagers and end users by respecting common user-defined variables such as `CC`, `AR`, `{C,LD}FLAGS`. Now the build system correctly applies the prefix to all install paths and lets users redefine them in a granular way.
This does not apply to Windows as I don't have enough experience with installation procedures on that OS. I'm happy to add further fixes.

I updated the library-related targets to install a versioned binary (both API and ABI wise) as it's commonly done.

Manpages are now uncompressed upon installation to allow for different compression algorithms and levels. Here's a link to a more eloquent explanation: https://cmpct.info/~sam/blog/posts/automatic-manpage-compression/

Add git to the build requirements as it's used to set the version string.

### CODE REVIEW

**Comment by antecrescent** [comment]
TODO:
- [ ] Respect `sysconfdir` for system-wide configuration files.
- [ ] Respect `libdir` for library path configuration (crucial for multi-lib setups!).
- [ ] Install `res/*` to `datarootdir` instead of to `/usr/lib/uwufetch` to conform to the [FHS](https://refspecs.linuxfoundation.org/fhs).
- [ ] Fix calling of package managers. Any of:
    - [ ] Call package managers from `$PATH` instead of relying on the absolute path. The current logic breaks setups with non-stardard/exotic executable command directories such as prefixed Gentoo Linux. This is imo the more sanest solution. 
    - [ ] Document `PKGPATH` and enforce it across the code base.

**Comment by TheDarkBug** [comment]
Thanks a lot for the contribution!
However, the Makefile in the development branch is a lot more updated, so the changes should have been made to that Makefile.
If you don't mind, it would be nice to update the development branch. I can do that myself if you can't or don't want to (I should have written about this in the readme, so it's my fault).

**Comment by antecrescent** [comment]
I take it that you approve of these changes? If so, I'll rebase my commits onto the development branch myself in the next couple of days. Thank you for the update!

**Comment by TheDarkBug** [comment]
Yes, I approve the changes

**Comment by TheDarkBug** [comment]
Do you have any updates on the progress?

**Comment by antecrescent** [comment]
Atm, university is taking up most of my time so unfortunately no progress has been made. I'll have time to work on this draft in March.
Sorry for the unannounced absence...

**Comment by TheDarkBug** [comment]
> Sorry for the unannounced absence...

No problem, I am actually in the same situation.

Good luck with your exams

**Pull request closed without merging**
